version: '3'
services:
  server:
    image: nginx:alpine
    volumes:
      - ./ops/config/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./web:/var/www/html
    ports:
      - 4000:80
    restart: always
  php:
    build:
      context: ./ops/docker/php
    volumes:
      - ./web:/var/www/html
